# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orar', '0003_auto_20170521_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elev',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, to='orar.Event'),
        ),
    ]
