# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orar', '0006_auto_20170522_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.IntegerField(choices=[(1, 'Luni'), (2, 'Marti'), (3, 'Miercuri'), (4, 'Joi'), (5, 'Vineri'), (6, 'Sambata'), (7, 'Duminica')], default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orar.Room'),
        ),
    ]
