# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orar', '0008_auto_20170522_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orar.Serie'),
        ),
    ]
