# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orar', '0012_event_tip_saptamana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupa',
            name='numar',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='numar_serie',
            field=models.IntegerField(unique=True),
        ),
    ]
